config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root 'products#index'

  resources :products, only: [:index, :create] do
    collection do
      get :statistics
    end
  end

  require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category_link.rb
class CategoryLink < ApplicationRecord
  validates :url, presence: true, uniqueness: true, url: true
  validate :url_must_belong_to_oz_by
  validate :url_mustnt_scraped_within_last_three_hours, if: :persisted?

  private

  def url_must_belong_to_oz_by
    uri = begin
      URI.parse(url)
    rescue StandardError
      nil
    end
    return unless uri && uri.host != 'oz.by'

    errors.add(:url, 'must belong to oz.by host')
  end

  def url_mustnt_scraped_within_last_three_hours
    errors.add(:url, 'scraped within last 3 hours') if updated_at > 3.hours.ago
  end
end

app/models/price_history.rb
class PriceHistory < ApplicationRecord
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :price_histories, dependent: :destroy

  scope :average_price_by_date, lambda { |start_date, end_date|
    dates = (start_date..end_date).map do |date|
      "AVG(CASE WHEN DATE(price_histories.created_at) = '#{date}' THEN price_histories.price_new ELSE NULL END)"
    end.join(', ')
    joins(:price_histories)
      .where('DATE(price_histories.created_at) BETWEEN ? AND ?', start_date, end_date)
      .group(:id, :link, :name, :image_url)
      .select(:id, :link, :name, :image_url, "ARRAY[#{dates}] AS average_prices")
      .order(:name)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Pagy::Backend

  def index; end

  def create
    urls = extract_urls_from_params
    invalid_urls = validate_category_links(urls)

    if invalid_urls.present?
      flash[:error] = format_error_messages(invalid_urls)
      render :index, status: :unprocessable_content
    else
      CategoryLink.transaction do
        @category_links.each(&:save)
      end
      @category_links.each do |link|
        ScrapJob.perform_async(link.url)
      end
      flash[:info] = t('.info')
      redirect_to root_path
    end
  end

  def statistics
    respond_to do |format|
      format.html
      format.turbo_stream do
        @info = params[:info]
        @start_date = params[:start_date]&.to_date
        @end_date = params[:end_date]&.to_date
        @date_range = @start_date..@end_date
        @pagy, @result = pagy(statistics_products(@info).average_price_by_date(@start_date, @end_date), limit: 10)
      end
    end
  end

  private

  def extract_urls_from_params
    @urls = params[:urls]
    @urls.to_s.split("\n").map(&:strip).uniq
  end

  def validate_category_links(urls)
    urls.each_with_object({}) do |url, invalid_urls|
      category_link = CategoryLink.find_or_initialize_by(url:)
      if category_link.valid?
        @category_links ||= []
        @category_links << category_link
      else
        invalid_urls[url] = category_link.errors.full_messages
      end
    end
  end

  def format_error_messages(invalid_urls)
    invalid_urls.map do |url, messages|
      "URL: #{url} - Errors: #{messages.join(', ')}"
    end
  end

  def statistics_products(info)
    if CategoryLink.find_or_initialize_by(url: info).valid?
      Product.where(link: info)
    else
      Product.where('name LIKE ?', "%#{Product.sanitize_sql_like(info)}%")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/application/_header.html.erb
<nav class="navbar fixed-top bg-body-tertiary">
  <form class="container-fluid justify-content-start">
    <%= link_to "Scrap", root_path, class: "btn btn-outline-success me-2" %>
    <%= link_to "Statistics", statistics_products_path, class: "btn btn-sm btn-outline-secondary" %>
  </form>
</nav>

app/views/application/_toast.html.erb
<% flash.each do |type, msg| %>
  <div class="position-fixed bottom-0 end-0 p-3" data-controller="toast">
    <div class="toast w-auto
                <%= 'bg-success text-light' if type == 'success' %>
                <%= 'bg-danger text-light' if type == 'error' %>
                <%= 'bg-warning text-light' if type == 'warning' %>
                <%= 'bg-info text-dark' if type == 'info' %>"
         role="alert" aria-live="assertive" aria-atomic="true" data-toast-target='toast'>
      <div class="toast-header">
        <strong class="me-auto"> <%= type.capitalize %> </strong>
        <small>just now</small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body">
        <% if msg.is_a?(Array) %>
          <ul>
            <% msg.each do |e| %>
              <li><%= e %></li>
            <% end %>
          </ul>
        <% else %>
          <%= msg %>
        <% end %>
      </div>
    </div>
  </div>
  <% flash.discard(type) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OzPriceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'header' %>
    <div class="container-fluid" style="margin-top: 70px;">
      <%= yield %>
    </div>
    <%= render 'toast' %>
  </body>
</html>

app/views/products/_pagination.html.erb
<nav aria-label="Pagination">
  <ul class="pagination justify-content-center">
    <% if @pagy.prev %>
      <li class="page-item">
        <%= link_to 'Prev',
                    statistics_products_path(page: @pagy.prev, info: @info, start_date: @start_date, end_date: @end_date),
                    data: { turbo_stream: true }, class: 'page-link' %>
      </li>
    <% end %>
    <li class="page-item active">
      <span class="page-link"><%= @pagy.page %></span>
    </li>
    <% if @pagy.next %>
      <li class="page-item">
        <%= link_to 'Next',
                    statistics_products_path(page: @pagy.next, info: @info, start_date: @start_date, end_date: @end_date),
                    data: { turbo_stream: true }, class: 'page-link' %>
      </li>
    <% end %>
  </ul>
</nav>
<p class="text-body-secondary"><%== pagy_info @pagy %></p>

app/views/products/_statistics_table.html.erb
<% if @result.present? %>
  <table class="table table-striped table-hover mt-3" style="overflow-x: auto;">
    <thead class="table-dark">
    <tr>
      <th scope="col">Product</th>
      <% date_range.each do |date| %>
        <th scope="col"><%= date.strftime("%Y-%m-%d") %></th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @result.each do |row| %>
      <tr>
        <td>
          <%= link_to image_tag(row.image_url, size: '50x50'), row.link, target: '_blank', class: 'img-fluid' %>
          <br>
          <%= link_to row.name, row.link, target: '_blank' %>
        </td>
        <% row.average_prices.each do |avg_price| %>
          <td><%= avg_price.present? ? number_with_precision(avg_price, precision: 2) : '-' %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info text-center mt-3" role="alert">
    No data
  </div>
<% end %>

app/views/products/index.html.erb
<div class="container mt-5">
  <h2 class="text-center mb-4">Scrap products</h2>
  <%= form_with url: products_path, method: :post, class: 'form-inline justify-content-center' do |form| %>
    <div class="form-group">
      <%= form.text_area :urls, class: 'form-control', rows: 5, placeholder: 'URLs)', required: true, value: @urls %>
    </div>
    <%= form.submit 'Scrap', class: 'btn btn-primary ml-2 mt-3' %>
  <% end %>
</div>

app/views/products/statistics.html.erb
<h2 class="text-center mb-4">Statistics</h2>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= form_with url: statistics_products_path, method: :get, data: { turbo_stream: true } do |form| %>
        <div class="input-group mb-3">
          <%= form.text_field :info, class: "form-control", placeholder: "Info", aria_label: "Info", required: true %>
        </div>
        <div class="input-group mb-3">
          <%= form.date_field :start_date, class: "form-control", required: true %>
          <%= form.date_field :end_date, class: "form-control", required: true %>
        </div>
        <%= form.submit "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
    <div id="statistics_table">
    </div>
    <%= turbo_frame_tag 'table_pagination' %>
  </div>
</div>

app/views/products/statistics.turbo_stream.erb
<%= turbo_stream.update 'statistics_table', partial: 'statistics_table',
                        locals: { result: @result, date_range: @date_range } %>
<%= turbo_stream.update 'table_pagination', partial: 'pagination' %>